package com.harsh.fittrack.di

import android.content.Context
import com.harsh.fittrack.data.local.DatabaseFactory
import com.harsh.fittrack.data.remote.auth.AndroidOAuthCredentialProvider
import com.harsh.fittrack.data.remote.auth.OAuthCredentialProvider
import org.koin.core.module.Module
import org.koin.dsl.module

/**
 * Android platform bindings. Pass into [initKoin] from `MainActivity` / `Application`:
 *
 * ```
 * initKoin { modules(androidModule(applicationContext, BuildConfig.WEB_CLIENT_ID)) }
 * ```
 *
 * [webClientId] is the **Web** OAuth client ID generated by Firebase for your project
 * (Firebase Console → Project settings → Web SDK configuration → Web client ID).
 */
fun androidModule(context: Context, webClientId: String): Module = module {
    single { DatabaseFactory(context.applicationContext) }
    single<OAuthCredentialProvider> { AndroidOAuthCredentialProvider(context.applicationContext, webClientId) }
}
